// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl3ps7XC5m5nFvLskYowjUhP7UiZ0xxM4',
    appId: '1:305537449390:web:8a038b895a09aba9561c3f',
    messagingSenderId: '305537449390',
    projectId: 'ticketbookingapp-358c8',
    authDomain: 'ticketbookingapp-358c8.firebaseapp.com',
    storageBucket: 'ticketbookingapp-358c8.appspot.com',
    measurementId: 'G-Y27BVYDRPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_gaoqFUVd5UqjUjCG_grp0D0R5yKSBVY',
    appId: '1:305537449390:android:41c1649e3f99e4a3561c3f',
    messagingSenderId: '305537449390',
    projectId: 'ticketbookingapp-358c8',
    storageBucket: 'ticketbookingapp-358c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKF__QkifGMz07nAb0JG3KAwTcKUAW2KE',
    appId: '1:305537449390:ios:1e605d79a96d7ef1561c3f',
    messagingSenderId: '305537449390',
    projectId: 'ticketbookingapp-358c8',
    storageBucket: 'ticketbookingapp-358c8.appspot.com',
    iosBundleId: 'com.example.ticketbookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKF__QkifGMz07nAb0JG3KAwTcKUAW2KE',
    appId: '1:305537449390:ios:46e4ab44fa666e0a561c3f',
    messagingSenderId: '305537449390',
    projectId: 'ticketbookingapp-358c8',
    storageBucket: 'ticketbookingapp-358c8.appspot.com',
    iosBundleId: 'com.example.ticketbookapp.RunnerTests',
  );
}
